import Head from 'next/head'
import axios from "axios"
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

export default function Home() {

  const url = `https://pokeapi.co/api/v2/pokemon?limit=30`

  const [data, setData] = useState<IPokemon[]>([]);

  useEffect(() => {
    const getData = async () => {
      const response = await axios.get(url);
      console.log(response);
      console.log(response.data.results)
      setData(response.data.results)
    }

    getData()
    // to catch any errors
    .catch(console.error)
  }, [])

  return (
    <>
      <Head>
        <title>PokeFormula</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
       
        {
          data && data.map((p, index) => {
            return(
              <div key={index}>
                <h1>{p.name}</h1>
              </div>
            )
          })
        }

      </main>
    </>
  )
}
